### ISSUE TITLE
ECC calibration problem

### ISSUE THREAD

**Issue by SmartSmallBoy** [azure-rtos/levelx#10]
Hello! In the process of using it, I found that page 0 will be written many times in “lx_nand_flash_open.c ". On lines 286 and 296, I can only block the ECC verification on page 0 before I can use it normally.

**Comment by bhnaphade** [comment]
Hi @SmartSmallBoy,  We will be working on a fix.

**Comment by zbqxyz** [comment]
> 
> 
> Hello! In the process of using it, I found that page 0 will be written many times in “lx_nand_flash_open.c ". On lines 286 and 296, I can only block the ECC verification on page 0 before I can use it normally.

Is this problem solved?

**Comment by zbqxyz** [comment]
> 
> 
> Hi @SmartSmallBoy, We will be working on a fix.

hi @bhnaphade Is this problem solved?

**Comment by SmartSmallBoy** [comment]
Hi！It seems not. I read the code of this function in version 6.18 and there is no change


---Original---
From: ***@***.***&gt;
Date: Mon, Aug 23, 2021 10:43 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [azure-rtos/levelx] ECC calibration problem (#10)




  
Hello! In the process of using it, I found that page 0 will be written many times in “lx_nand_flash_open.c ". On lines 286 and 296, I can only block the ECC verification on page 0 before I can use it normally.
  
Is this problem solved?
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bhnaphade** [comment]
We are currently working on the issue
