### ISSUE TITLE
Possible array out of bound in lx_nor_flash_extended_cache array

### ISSUE THREAD

**Issue by Eladov** [azure-rtos/levelx#11]
The function _lx_nor_flash_driver_read has a section that iterates over the  `lx_nor_flash_extended_cache` array

https://github.com/azure-rtos/levelx/blob/61f92c00c74ebe8c5798652b756115cc8995b894/common/src/lx_nor_flash_driver_read.c#L107-L155

this Array is of size LX_NOR_EXTENDED_CACHE_SIZE which is set to 8, but the for loop iterates till `lx_nor_flash_extended_cache_entries`

the `lx_nor_flash_extended_cache_entries` value is set in the `_lx_nor_flash_extended_cache_enable` function, and is basically the number of sector sized chunks from the given ram Cache

https://github.com/azure-rtos/levelx/blob/61f92c00c74ebe8c5798652b756115cc8995b894/common/src/lx_nor_flash_extended_cache_enable.c#L117-L139

If the user gives a cache in the size of more than `LX_NOR_EXTENDED_CACHE_SIZE` sectors this may lead to exceeding the size of the `lx_nor_flash_extended_cache` array.

Maybe some sort of input validation should be added to make sure the given ram memory isn't too big?

**Comment by bhnaphade** [comment]
Thank you for the feedback. We will review this internally

**Comment by bhnaphade** [comment]
We have added a check for boundary and the fix will be available in the next release.

**Comment by Eladov** [comment]
Thanks
