### ISSUE TITLE
The problem of levelX's block recovery of nand flash

### ISSUE THREAD

**Issue by aod-ad** [azure-rtos/levelx#8]
UINT  _lx_nand_flash_block_reclaim(LX_NAND_FLASH *nand_flash)
{
...
if (obsolete_pages == nand_flash->lx_nand_flash_pages_per_block)
...
}

obsolete_pages cannot exceed (nand_flash->lx_nand_flash_pages_per_block-1), Because the first page is used as the mapping list.

**Comment by xiuwencai** [comment]
Thank you for the feedback, this is a bug in the code. We will fix it.

**Comment by bhnaphade** [comment]
This is fixed in Azure RTOS release 6.1.8
